export const CATEGORIES = [
  { id: 'todos', label: 'Todos los productos' },
  { id: 'ternera', label: 'Novillito & Ternera' },
  { id: 'cerdo', label: 'Cortes de Cerdo' },
  { id: 'pollo', label: 'Pollo de Campo' },
  { id: 'achuras', label: 'Achuras & Embutidos' },
  { id: 'vinos', label: 'Vinos de Selección' },
]

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Ojo de Bife Angus',
    category: 'ternera',
    categoryLabel: 'Novillito',
    price: 13900,
    unit: 'kg',
    stock: 15,
    description: 'Corte tierno, con excelente marmoleado y jugosidad inigualable.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/-2020-20-22_Two_cuts_of_rib_eye_beef_steak%2C_Trimingham.JPG/960px--2020-20-22_Two_cuts_of_rib_eye_beef_steak%2C_Trimingham.JPG',
  },
  {
    id: 2,
    name: 'Bife de Chorizo Premium',
    category: 'ternera',
    categoryLabel: 'Novillito',
    price: 12400,
    unit: 'kg',
    stock: 22,
    description: 'Clásico corte argentino con la grasa perimetral justa para la parrilla.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 3,
    name: 'Asado de Tira Especial',
    category: 'ternera',
    categoryLabel: 'Novillito',
    price: 10500,
    unit: 'kg',
    stock: 30,
    description: 'Costillar cortado a lo ancho, sabor profundo y crocancia al fuego.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 4,
    name: 'Entraña Fina Seleccionada',
    category: 'ternera',
    categoryLabel: 'Novillito',
    price: 16800,
    unit: 'kg',
    stock: 8,
    description: 'Corte estrella de cocción rápida, crocante por fuera y tierno por dentro.',
    image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 5,
    name: 'Matambre de Cerdo',
    category: 'cerdo',
    categoryLabel: 'Cerdo',
    price: 8900,
    unit: 'kg',
    stock: 14,
    description: 'Ideal para dorar a fuego vivo con limón y hierbas frescas.',
    image: 'https://live.staticflickr.com/7097/13333162204_69c3c3bee3_b.jpg',
  },
  {
    id: 6,
    name: 'Bondiola de Cerdo',
    category: 'cerdo',
    categoryLabel: 'Cerdo',
    price: 7800,
    unit: 'kg',
    stock: 19,
    description: 'Tierna y veteada, perfecta para asar entera o en medallones.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Schweinenacken-1.jpg/960px-Schweinenacken-1.jpg',
  },
  {
    id: 7,
    name: 'Pollo de Campo Pastoril',
    category: 'pollo',
    categoryLabel: 'Pollo',
    price: 4900,
    unit: 'kg',
    stock: 25,
    description: 'Criado en libertad sin hormonas, carne firme y sabor auténtico.',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 8,
    name: 'Chorizo Puro Criollo (x4)',
    category: 'achuras',
    categoryLabel: 'Embutidos',
    price: 6200,
    unit: 'pack',
    stock: 18,
    description: 'Receta tradicional 80/20 con pimentón dulce y vino blanco.',
    image: 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 9,
    name: 'Mollejas de Corazón',
    category: 'achuras',
    categoryLabel: 'Achuras',
    price: 15400,
    unit: 'kg',
    stock: 6,
    description: 'La reina de las achuras, textura sedosa y suave tostado a las brasas.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Kalbsbries_1.jpg/960px-Kalbsbries_1.jpg',
  },
  {
    id: 10,
    name: 'Gran Reserva Malbec 2021',
    category: 'vinos',
    categoryLabel: 'Vinos',
    price: 14200,
    unit: 'botella',
    stock: 12,
    description: 'Valle de Uco, Mendoza. Maridaje perfecto para carnes rojas a la brasa.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
  },
]
